import localFont from "next/font/local";
import { Poppins } from 'next/font/google';
import { Providers } from "./providers";
import "./globals.css";

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${poppins.variable} ${poppins.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${poppins.variable} antialiased`}>
//         <UserProvider>
//           <ToastProvider>
//             {children}
//           </ToastProvider>
//         </UserProvider>
//       </body>
//     </html>
//   );
// }
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}